version: '3.8'

services:
  postgres_service:
    image: postgres:14.6
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: userDB
    ports:
      - "5432:5432"